### ISSUE TITLE
Error: PluginList: Parsing

### ISSUE THREAD

**Issue by MiG-41** [MarFanNL/HeishamonMQTT#10]
Thank you @MarFanNL for this plugin. 
I tried to install it ,to test it on my RPi Zero , and after upgrade to the newest domoticz beta , update/upgrade rasbian , check of python version ( 3.7.3 ) , checking that python3-dev is installed , 

I got the message in log (after going to Configuration /Hardware) an error:
'
2021-02-05 23:16:20.460 Error: PluginList: Parsing '/home/pi/domoticz/plugins/HeishamonMQTT/', 'Error document empty.' at line 0 column 0 in XML ''. 
'
And HeishamonMQT i not on the list.

In directory of plugins i have a directory HeishamonMQTT ,and it is not empty. Files are downloaded directly from Git via wget command , and after that i do chmod 777 , :

drwxr-xr-x 2 pi pi   4096 Feb  5 22:07 .
drwxr-xr-x 5 pi pi   4096 Nov  9 13:47 ..
-rwxrwxrwx 1 pi pi 145665 Feb  5 22:07 mqtt.py
-rwxrwxrwx 1 pi pi 273422 Feb  5 22:07 plugin.py

After that i decided to download the newest ubuntu server LTS , and installed it on old laptop , and installed domoticz , phyton ,ect , and got exacly the same case.  Different here is ,that python is 3.8.5 version.
Maybe i made some reapeted error....

**Comment by MiG-41** [comment]
Ok , now i got it , downloading by wget files directly wend wrong... I used ling from web page , and it downloaded some bigger files. Do you know a hint ,how to download files from git directly to directory ?

**Comment by IgorYbema** [comment]
git clone https://github.com/MarFanNL/HeishamonMQTT.git
:-)

**Comment by MiG-41** [comment]
Yes , Please write more precisie instruction for noob :)

Thank you !
